<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{571dcd2b-7f1a-0119-09ce-d4765fa24bb1}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	jsonDomParser_TestSuit : JsonDomParser_TestSuit;
	jsonSerializer_TestSuite : JsonSerializer_TestSuite;
	jsonDeserializer_TestSuite : JsonDeserializer_TestSuite;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>